package studio.seer.lineage.resource;

import io.smallrye.mutiny.Uni;
import jakarta.inject.Inject;
import org.eclipse.microprofile.graphql.*;
import studio.seer.lineage.heimdall.HeimdallEmitter;
import studio.seer.lineage.heimdall.model.EventLevel;
import studio.seer.lineage.heimdall.model.EventType;
import studio.seer.lineage.model.*;
import studio.seer.lineage.security.SeerIdentity;
import studio.seer.lineage.service.*;

import java.util.Map;

import java.util.List;

/**
 * GraphQL API for SEER LOOM — three view levels + search.
 *
 * All queries are intent-based: the client never sends raw Cypher/SQL.
 * Role enforcement is in SeerIdentity (via X-Seer-Role from rbac-proxy).
 *
 * Schema auto-generated by SmallRye GraphQL from method signatures.
 * Browse at http://localhost:8080/graphql-ui in dev mode.
 */
@GraphQLApi
public class LineageResource {

    @Inject SeerIdentity    identity;
    @Inject OverviewService overviewService;
    @Inject ExploreService  exploreService;
    @Inject LineageService  lineageService;
    @Inject SearchService   searchService;
    @Inject HeimdallEmitter heimdall;

    // ── L1: Overview ──────────────────────────────────────────────────────────

    @Query("overview")
    @Description("L1 — aggregated list of schemas with counts. Role: viewer+")
    public Uni<List<SchemaNode>> overview() {
        long start = System.currentTimeMillis();
        heimdall.emit(EventType.REQUEST_RECEIVED, EventLevel.INFO,
                null, null, 0, Map.of("op", "overview", "call", "overview()"));
        return overviewService.overview()
                .invoke(results -> heimdall.emit(EventType.REQUEST_COMPLETED, EventLevel.INFO,
                        null, null, System.currentTimeMillis() - start,
                        Map.of("op", "overview",
                               "schemaCount", results != null ? results.size() : 0,
                               "call", "overview() → " + (results != null ? results.size() : 0) + " schemas")));
    }

    // ── L2: Explore ───────────────────────────────────────────────────────────

    @Query("explore")
    @Description("L2 — tables and routines within a schema or package scope. Role: viewer+")
    public Uni<ExploreResult> explore(
        @Name("scope")
        @Description("'schema-<name>', 'pkg-<name>', or a raw @rid")
        String scope,
        @Name("includeExternal") @DefaultValue("false")
        @Description("When true, also fetch READS_FROM / WRITES_TO / DATA_FLOW / FILTER_FLOW edges whose table endpoint is in a DIFFERENT schema. Default false (current schema only).")
        Boolean includeExternal
    ) {
        long start = System.currentTimeMillis();
        boolean ext = includeExternal != null && includeExternal;
        heimdall.emit(EventType.REQUEST_RECEIVED, EventLevel.INFO,
                null, null, 0,
                Map.of("op", "explore", "scope", scope != null ? scope : "",
                       "includeExternal", ext,
                       "call", call("explore", "scope", scope != null ? scope : "") + (ext ? " +external" : "")));
        return exploreService.explore(scope, ext)
                .invoke(result -> heimdall.emit(EventType.REQUEST_COMPLETED, EventLevel.INFO,
                        null, null, System.currentTimeMillis() - start,
                        Map.of("op",    "explore",
                               "scope", scope != null ? scope : "",
                               "includeExternal", ext,
                               "nodes", result != null ? result.nodes().size() : 0,
                               "edges", result != null ? result.edges().size() : 0,
                               "call",  call("explore", "scope", scope != null ? scope : "") + (ext ? " +external" : "")
                                        + " → " + (result != null ? result.nodes().size() : 0) + " nodes, "
                                        + (result != null ? result.edges().size() : 0) + " edges")));
    }

    // ── L2+: Statement column enrichment ─────────────────────────────────────

    @Query("stmtColumns")
    @Description("Bulk HAS_OUTPUT_COL + HAS_AFFECTED_COL for a list of statement @rids. Role: viewer+")
    public Uni<ExploreResult> stmtColumns(
        @Name("ids")
        @Description("List of statement @rids returned by explore")
        List<String> ids
    ) {
        long start = System.currentTimeMillis();
        heimdall.emit(EventType.REQUEST_RECEIVED, EventLevel.INFO,
                null, null, 0,
                Map.of("op", "stmtColumns", "count", ids != null ? ids.size() : 0,
                       "call", call("stmtColumns", "in", ids != null ? ids.size() : 0)));
        return exploreService.exploreStmtColumns(ids)
                .invoke(result -> heimdall.emit(EventType.REQUEST_COMPLETED, EventLevel.INFO,
                        null, null, System.currentTimeMillis() - start,
                        Map.of("op",    "stmtColumns",
                               "in",    ids != null ? ids.size() : 0,
                               "nodes", result != null ? result.nodes().size() : 0,
                               "edges", result != null ? result.edges().size() : 0,
                               "call",  call("stmtColumns", "in", ids != null ? ids.size() : 0)
                                        + " → " + (result != null ? result.nodes().size() : 0) + " nodes")));
    }

    // ── L3: Column lineage ────────────────────────────────────────────────────

    @Query("lineage")
    @Description("L3 — full bidirectional column lineage for a node. Role: viewer+")
    public Uni<ExploreResult> lineage(
        @Name("nodeId")
        @Description("@rid of a DaliTable or DaliColumn vertex")
        String nodeId
    ) {
        long start = System.currentTimeMillis();
        heimdall.emit(EventType.REQUEST_RECEIVED, EventLevel.INFO,
                null, null, 0,
                Map.of("op", "lineage", "nodeId", nodeId != null ? nodeId : "",
                       "call", call("lineage", "nodeId", nodeId != null ? nodeId : "")));
        return lineageService.lineage(nodeId)
                .invoke(result -> heimdall.emit(EventType.REQUEST_COMPLETED, EventLevel.INFO,
                        null, null, System.currentTimeMillis() - start,
                        Map.of("op",     "lineage",
                               "nodeId", nodeId != null ? nodeId : "",
                               "nodes",  result != null ? result.nodes().size() : 0,
                               "edges",  result != null ? result.edges().size() : 0,
                               "call",   call("lineage", "nodeId", nodeId != null ? nodeId : "")
                                         + " → " + (result != null ? result.nodes().size() : 0) + " nodes, "
                                         + (result != null ? result.edges().size() : 0) + " edges")));
    }

    @Query("upstream")
    @Description("L3 — upstream lineage only (what feeds into this node). Role: viewer+")
    public Uni<ExploreResult> upstream(@Name("nodeId") String nodeId) {
        long start = System.currentTimeMillis();
        heimdall.emit(EventType.REQUEST_RECEIVED, EventLevel.INFO,
                null, null, 0,
                Map.of("op", "upstream", "nodeId", nodeId != null ? nodeId : "",
                       "call", call("upstream", "nodeId", nodeId != null ? nodeId : "")));
        return lineageService.upstream(nodeId)
                .invoke(result -> heimdall.emit(EventType.REQUEST_COMPLETED, EventLevel.INFO,
                        null, null, System.currentTimeMillis() - start,
                        Map.of("op",     "upstream",
                               "nodeId", nodeId != null ? nodeId : "",
                               "nodes",  result != null ? result.nodes().size() : 0,
                               "edges",  result != null ? result.edges().size() : 0,
                               "call",   call("upstream", "nodeId", nodeId != null ? nodeId : "")
                                         + " → " + (result != null ? result.nodes().size() : 0) + " nodes, "
                                         + (result != null ? result.edges().size() : 0) + " edges")));
    }

    @Query("downstream")
    @Description("L3 — downstream impact (what this node affects). Role: viewer+")
    public Uni<ExploreResult> downstream(@Name("nodeId") String nodeId) {
        long start = System.currentTimeMillis();
        heimdall.emit(EventType.REQUEST_RECEIVED, EventLevel.INFO,
                null, null, 0,
                Map.of("op", "downstream", "nodeId", nodeId != null ? nodeId : "",
                       "call", call("downstream", "nodeId", nodeId != null ? nodeId : "")));
        return lineageService.downstream(nodeId)
                .invoke(result -> heimdall.emit(EventType.REQUEST_COMPLETED, EventLevel.INFO,
                        null, null, System.currentTimeMillis() - start,
                        Map.of("op",     "downstream",
                               "nodeId", nodeId != null ? nodeId : "",
                               "nodes",  result != null ? result.nodes().size() : 0,
                               "edges",  result != null ? result.edges().size() : 0,
                               "call",   call("downstream", "nodeId", nodeId != null ? nodeId : "")
                                         + " → " + (result != null ? result.nodes().size() : 0) + " nodes, "
                                         + (result != null ? result.edges().size() : 0) + " edges")));
    }

    @Query("expandDeep")
    @Description("L2/L3 — multi-hop lineage (READS_FROM/WRITES_TO) up to `depth` hops both ways. Role: viewer+")
    public Uni<ExploreResult> expandDeep(
        @Name("nodeId") String nodeId,
        @Name("depth")  @DefaultValue("5") int depth
    ) {
        long start = System.currentTimeMillis();
        heimdall.emit(EventType.REQUEST_RECEIVED, EventLevel.INFO,
                null, null, 0,
                Map.of("op", "expandDeep", "nodeId", nodeId != null ? nodeId : "", "depth", depth,
                       "call", call("expandDeep", "nodeId", nodeId != null ? nodeId : "", "depth", depth)));
        return lineageService.expandDeep(nodeId, depth)
                .invoke(result -> heimdall.emit(EventType.REQUEST_COMPLETED, EventLevel.INFO,
                        null, null, System.currentTimeMillis() - start,
                        Map.of("op",     "expandDeep",
                               "nodeId", nodeId != null ? nodeId : "",
                               "nodes",  result != null ? result.nodes().size() : 0,
                               "edges",  result != null ? result.edges().size() : 0,
                               "call",   call("expandDeep", "nodeId", nodeId != null ? nodeId : "", "depth", depth)
                                         + " → " + (result != null ? result.nodes().size() : 0) + " nodes, "
                                         + (result != null ? result.edges().size() : 0) + " edges")));
    }

    // ── Search ────────────────────────────────────────────────────────────────

    @Query("search")
    @Description("Full-text search across tables, columns, routines. Role: viewer+")
    public Uni<List<SearchResult>> search(
        @Name("query") String query,
        @Name("limit") @DefaultValue("20") int limit
    ) {
        long start = System.currentTimeMillis();
        heimdall.emit(EventType.REQUEST_RECEIVED, EventLevel.INFO,
                null, null, 0,
                Map.of("op", "search", "q", query != null ? query : "",
                       "call", call("search", "q", query != null ? query : "", "limit", Math.min(limit, 100))));
        return searchService.search(query, Math.min(limit, 100))
                .invoke(results -> heimdall.emit(EventType.REQUEST_COMPLETED, EventLevel.INFO,
                        null, null, System.currentTimeMillis() - start,
                        Map.of("op",   "search",
                               "q",    query != null ? query : "",
                               "hits", results != null ? results.size() : 0,
                               "call", call("search", "q", query != null ? query : "")
                                       + " → " + (results != null ? results.size() : 0) + " hits")));
    }

    // ── Meta ──────────────────────────────────────────────────────────────────

    @Query("me")
    @Description("Current identity as seen by lineage-api")
    public String me() {
        return identity.username() + " (" + identity.role() + ")";
    }

    // ── Internal ──────────────────────────────────────────────────────────────

    /** Builds a readable call signature like {@code explore(scope=schema-PROD)}. */
    private static String call(String op, Object... kv) {
        var sb = new StringBuilder(op).append('(');
        for (int i = 0; i < kv.length - 1; i += 2) {
            if (i > 0) sb.append(", ");
            sb.append(kv[i]).append('=').append(kv[i + 1]);
        }
        return sb.append(')').toString();
    }
}
