// TODO: remove when API ready — UsersPage fetches from /heimdall/users (Keycloak)
// Quotas + sources still mocked until FRIGG R4.3 is wired.
import type { AidaUser } from './types';

export const MOCK_USERS: AidaUser[] = [
  {
    id: 1, name: 'admin', email: 'admin@seer.io', role: 'admin', active: true,
    title: 'Platform Engineer', dept: 'Platform', phone: '+7 900 111-00-01',
    sources: [],
    quotas: { mimir: 100, sessions: 10, atoms: 100000, workers: 8, anvil: 200 },
    lastActive: 'только что',
    sessions: { used: 1, total: 142 },
    mimir:    { used: 8, total: 89 },
    prefs: {
      lang: 'ru', tz: 'Europe/Moscow', dateFmt: 'DD.MM.YYYY',
      startPage: 'dashboard', avatarColor: '#A8B860',
      notifyEmail: true, notifyBrowser: false, notifyHarvest: true,
      notifyErrors: true, notifyDigest: false,
    },
  },
  {
    id: 2, name: 'alexey.petrov', email: 'a.petrov@seer.io', role: 'operator', active: true,
    title: 'Data Ops Engineer', dept: 'Analytics', phone: '+7 900 222-00-02',
    sources: ['Oracle CRM Production', 'Oracle ERP'],
    quotas: { mimir: 50, sessions: 3, atoms: 50000, workers: 4, anvil: 50 },
    lastActive: '1ч назад',
    sessions: { used: 0, total: 28 },
    mimir:    { used: 12, total: 47 },
    prefs: {
      lang: 'ru', tz: 'Europe/Moscow', dateFmt: 'DD.MM.YYYY',
      startPage: 'events', avatarColor: '#D4922A',
      notifyEmail: true, notifyBrowser: true, notifyHarvest: true,
      notifyErrors: true, notifyDigest: false,
    },
  },
  {
    id: 3, name: 'editor', email: 'm.kuznetsova@seer.io', role: 'editor', active: true,
    title: 'Data Analyst', dept: 'BI', phone: '',
    sources: [],
    quotas: { mimir: 20, sessions: 0, atoms: 0, workers: 0, anvil: 20 },
    lastActive: '3ч назад',
    sessions: { used: 0, total: 0 },
    mimir:    { used: 5, total: 31 },
    prefs: {
      lang: 'ru', tz: 'Europe/Kiev', dateFmt: 'YYYY-MM-DD',
      startPage: 'loom', avatarColor: '#88B8A8',
      notifyEmail: true, notifyBrowser: false, notifyHarvest: false,
      notifyErrors: true, notifyDigest: true,
    },
  },
  {
    id: 4, name: 'sergey.ivanov', email: 's.ivanov@seer.io', role: 'auditor', active: true,
    title: 'Security Auditor', dept: 'Security', phone: '+7 900 444-00-04',
    sources: [],
    quotas: { mimir: 0, sessions: 0, atoms: 0, workers: 0, anvil: 0 },
    lastActive: 'вчера',
    sessions: { used: 0, total: 0 },
    mimir:    { used: 0, total: 2 },
    prefs: {
      lang: 'ru', tz: 'Europe/Moscow', dateFmt: 'DD.MM.YYYY',
      startPage: 'dashboard', avatarColor: '#afa9ec',
      notifyEmail: false, notifyBrowser: false, notifyHarvest: false,
      notifyErrors: false, notifyDigest: true,
    },
  },
  {
    id: 5, name: 'tenant.owner', email: 'owner@acme.com', role: 'tenant-owner', active: true,
    title: 'CTO', dept: 'Management', phone: '+7 900 555-00-05',
    sources: [],
    quotas: { mimir: 50, sessions: 5, atoms: 75000, workers: 6, anvil: 100 },
    lastActive: '2д назад',
    sessions: { used: 0, total: 12 },
    mimir:    { used: 3, total: 18 },
    prefs: {
      lang: 'en', tz: 'UTC', dateFmt: 'MM/DD/YYYY',
      startPage: 'dashboard', avatarColor: '#f0997b',
      notifyEmail: true, notifyBrowser: false, notifyHarvest: false,
      notifyErrors: true, notifyDigest: true,
    },
  },
  {
    id: 6, name: 'local.admin', email: 'la@acme.com', role: 'local-admin', active: true,
    title: 'Team Lead', dept: 'Analytics', phone: '',
    sources: ['PostgreSQL Analytics'],
    quotas: { mimir: 50, sessions: 5, atoms: 75000, workers: 6, anvil: 100 },
    lastActive: '5ч назад',
    sessions: { used: 0, total: 6 },
    mimir:    { used: 1, total: 9 },
    prefs: {
      lang: 'ru', tz: 'Asia/Yekaterinburg', dateFmt: 'DD.MM.YYYY',
      startPage: 'services', avatarColor: '#5dcaa5',
      notifyEmail: true, notifyBrowser: true, notifyHarvest: true,
      notifyErrors: true, notifyDigest: false,
    },
  },
  {
    id: 7, name: 'viewer', email: 'dev@seer.io', role: 'viewer', active: false,
    title: 'Junior Developer', dept: 'Dev', phone: '',
    sources: ['PostgreSQL Analytics'],
    quotas: { mimir: 5, sessions: 0, atoms: 0, workers: 0, anvil: 0 },
    lastActive: '5д назад',
    sessions: { used: 0, total: 0 },
    mimir:    { used: 0, total: 0 },
    prefs: {
      lang: 'ru', tz: 'Europe/Moscow', dateFmt: 'YYYY-MM-DD',
      startPage: 'loom', avatarColor: '#7DBF78',
      notifyEmail: false, notifyBrowser: false, notifyHarvest: false,
      notifyErrors: false, notifyDigest: false,
    },
  },
];
