package studio.seer.lineage.heimdall.model;

/**
 * Local copy of studio.seer.shared.EventType for SHUTTLE.
 * Temporary until Docker multi-module build for SHUTTLE is implemented.
 * Keep in sync with shared/dali-models/EventType.java.
 *
 * Last sync: Sprint 5 Events (EV-04/EV-05 — CYPHER_QUERY_SLOW, DB_CONNECTION_ERROR).
 */
public enum EventType {
    // Hound
    FILE_PARSING_STARTED, FILE_PARSING_COMPLETED, FILE_PARSING_FAILED,
    PARSE_ERROR, PARSE_WARNING, SEMANTIC_WARNING, SEMANTIC_ERROR,
    ATOM_EXTRACTED, RESOLUTION_COMPLETED,

    // Dali
    SESSION_STARTED, SESSION_COMPLETED, SESSION_FAILED,
    WORKER_ASSIGNED, JOB_ENQUEUED, JOB_COMPLETED, COMPLEX_JOB_PROGRESS,

    // MIMIR
    QUERY_RECEIVED, TIER_SELECTED,
    TOOL_CALL_STARTED, TOOL_CALL_COMPLETED, LLM_RESPONSE_READY, CACHE_HIT,

    // ANVIL
    TRAVERSAL_STARTED, TRAVERSAL_PROGRESS, TRAVERSAL_COMPLETED,
    QUERY_EXECUTED, QUERY_BLOCKED,

    // SHUTTLE
    REQUEST_RECEIVED, REQUEST_COMPLETED, SUBSCRIPTION_OPENED,

    // YGG writes (Hound → YGG)
    YGG_WRITE_COMPLETED, YGG_WRITE_FAILED, YGG_CLEAR_COMPLETED,

    // SHUTTLE → YGG performance  (EV-04)
    CYPHER_QUERY_SLOW,

    // DB health (EV-05)
    DB_CONNECTION_ERROR,

    // Dali config audit
    SOURCE_CREATED, SOURCE_DELETED,

    // Verdandi / LOOM frontend
    LOOM_NODE_SELECTED, LOOM_VIEW_LOADED, LOOM_VIEW_SLOW,

    // Chur BFF auth audit
    AUTH_LOGIN, AUTH_LOGOUT, RATE_LIMIT_EXCEEDED,

    // HEIMDALL internal
    DEMO_RESET, SNAPSHOT_SAVED, REPLAY_STARTED
}
